// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naroalxhbrvmosbqzhrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hcm9hbHhoYnJ2bW9zYnF6aHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzMTIxNzIsImV4cCI6MjA4Mzg4ODE3Mn0.vJonqevyhTOG673oD7v2NNiioau709b9UCfyqNIRDMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});